Added Muslim Aid bake sale fundraising event
SwanseaCompSci/tree-society-website pull request #49
Opened 2023-11-02 18:09 UTC by RalphLynch

## Describe your changes
I added the recent bake sale for Muslim Aid to the fundraising section, and updated the fundraising total accordingly.
## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my changes
- [x] I have made corresponding changes to the documentation and comments where neccessary
- [x] If the changes affect the website, I have tested the branch using `bundle exec jekyll serve` on my local machine

2023-11-03 14:58 UTC, svejnohatomas commented
@RalphLynch Can you please assign yourself as an assignee and Nathan or me to the PRs as reviewers? We won't see it otherwise. Thanks

2023-11-03 15:27 UTC, svejnohatomas requested changes

2023-11-03 15:27 UTC, svejnohatomas commented on _data/sitetext.yml
>      total_funds_raised: 6415.00 # amount of funds raised in GBP
@RalphLynch Can you please also update the total? Thanks

2023-11-12 17:46 UTC, RalphLynch commented
Hi, sorry I took a while to get back to you, I've just been a bit busy with coursework. Also, apologies for not assigning you to the review earlier, it must have slipped my mind while making the PR.

2023-11-13 14:28 UTC, svejnohatomas approved these changes

2023-11-13 14:28 UTC, svejnohatomas commented
@RalphLynch Thank you. Approved.

2023-11-15 10:52 UTC, merged